---
- host: jenkins-slave
  become: true
  tasks:
    - name: update ubuntu repo and update_cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install java
      apt:
        name: openjdk-17-jre
        state: present

    - name: download maven packages
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
        dest: /opt

    - name: extract maven packages
      unarchive:
        src: /opt/apache-maven-3.9.9-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: configure maven environment variables
      copy:
        dest: /etc/profile.d/maven.sh
        content: |
          export MAVEN_HOME=/opt/apache-maven-3.9.9
          export PATH=$PATH:$MAVEN_HOME/bin
        mode: '0755'

    - name: source maven environment script
      shell: source /etc/profile.d/maven.sh
      args:
        executable: /bin/bash
